<?php

/**
 * @file
 * Contains calculadora.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function calculadora_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tbo_account module.
    case 'help.page.contacts_gmail_management':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Find exist user in DB') . '</p>';
      return $output;

    default:
  }
}

function calculadora_theme() {
  return [
    'calculadora' => [
      'variables' => [
		'form' => NULL,
	  ],
      'template' => 'calculadora',
    ]
  ];
}
